### ISSUE TITLE
Potentially add NCBI downloads instead

### ISSUE THREAD

**Issue by chriswyatt1** [Eco-Flow/excon#30]
https://nf-co.re/modules/ncbigenomedownload/

**Comment by FernandoDuarteF** [comment]
I get this error message after installing the module:

```
ERROR ~ Error executing process > 'NCBIGENOMEDOWNLOAD (2)'

Caused by:
  Process `NCBIGENOMEDOWNLOAD (2)` terminated with an error exit status (1)


Command executed:

  ncbi-genome-download \
       \
      -A GCF_011952205.1 \
       \
      --output-folder ./ \
      --flat-output \
      --parallel 2 \
      invertebrate

  cat <<-END_VERSIONS > versions.yml
  "NCBIGENOMEDOWNLOAD":
      ncbigenomedownload: $( ncbi-genome-download --version )
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
  Traceback (most recent call last):
    File "/usr/local/bin/ncbi-genome-download", line 10, in <module>
      sys.exit(main())
               ^^^^^^
    File "/usr/local/lib/python3.11/site-packages/ncbi_genome_download/__main__.py", line 26, in main
      ret = args_download(args)
            ^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/ncbi_genome_download/core.py", line 184, in args_download
      return config_download(config)
             ^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/ncbi_genome_download/core.py", line 203, in config_download
      download_candidates = select_candidates(config)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/ncbi_genome_download/core.py", line 316, in select_candidates
      summary_file = get_summary(config.section, group, config.uri, config.use_cache)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/ncbi_genome_download/core.py", line 422, in get_summary
      os.makedirs(CACHE_DIR)
    File "<frozen os>", line 215, in makedirs
    File "<frozen os>", line 225, in makedirs
  PermissionError: [Errno 13] Permission denied: '/.cache'

Work dir:
  /Users/fernando/work/repositories/excon/work/71/7ca07690966293b10c49bbdb940dfd

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
```

**Comment by FernandoDuarteF** [comment]
Runs ok in conda env using the command line:

```
ncbi-genome-download -A GCF_011952205.1 --output-folder ./ --flat-output --p
arallel 2 invertebrate
```

**Comment by FernandoDuarteF** [comment]
Done in [c542b20](https://github.com/Eco-Flow/excon/commit/c542b2005b8a740bb72fc351e827bbf49862309c)

**Comment by FernandoDuarteF** [comment]
Done in [c542b20](https://github.com/Eco-Flow/excon/commit/c542b2005b8a740bb72fc351e827bbf49862309c)
